In [60]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv(r"E:\data_cleaning\customer_churn_sample.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 15
Columns: 11

In [66]:
# Display the first 5 rows
df.head()
df.tail()

,CustomerID,Gender,Age,TenureMonths,SubscriptionType,MonthlyCharges,TotalCharges,ContractType,SupportTickets,PaymentMethod,Churn
10,CUST-1011,Female,49,30,Enterprise,149.99,4499.70,Two Year,0,Credit Card,No
11,CUST-1012,Male,33,14,Pro,79.99,1119.86,Month-to-Month,3,Debit Card,Yes
12,CUST-1013,Female,55,22,Basic,49.99,1099.78,One Year,1,Bank Transfer,No
13,CUST-1014,Male,26,2,Basic,49.99,99.98,Month-to-Month,5,UPI,Yes
14,CUST-1015,Female,43,40,Enterprise,149.99,5999.60,Two Year,1,Credit Card,No

In [67]:
print("Dataset shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

Dataset shape:
(15, 11)

Column names:
['CustomerID', 'Gender', 'Age', 'TenureMonths', 'SubscriptionType', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'SupportTickets', 'PaymentMethod', 'Churn']

In [68]:
# Remove unnecessary spaces
# Convert column names to lowercase
# Replace spaces with underscores

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df.columns.tolist())

['customerid', 'gender', 'age', 'tenuremonths', 'subscriptiontype', 'monthlycharges', 'totalcharges', 'contracttype', 'supporttickets', 'paymentmethod', 'churn']

In [69]:
# Count missing values in every column
missing_values = df.isnull().sum()

print("Missing values:")
print(missing_values)

Missing values:
customerid          0
gender              0
age                 0
tenuremonths        0
subscriptiontype    0
monthlycharges      0
totalcharges        0
contracttype        0
supporttickets      0
paymentmethod       0
churn               0
dtype: int64

In [70]:
categorical_columns = [
    "gender",
    "subscriptiontype",
    "contracttype",
    "paymentmethod",
    "churn"
]

In [71]:
# Remove leading/trailing spaces
for column in categorical_columns:
    df[column] = df[column].astype(str).str.strip()

print("Categorical spaces cleaned successfully!")

Categorical spaces cleaned successfully!

In [72]:
df["gender"] = (
    df["gender"]
    .str.strip()
    .str.lower()
    .str.capitalize()
)

print(df["gender"].unique())

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [73]:
df["subscriptiontype"] = (
    df["subscriptiontype"]
    .str.strip()
    .str.title()
)

print(df["subscriptiontype"].unique())

<StringArray>
['Basic', 'Pro', 'Enterprise']
Length: 3, dtype: str

In [74]:
df["contracttype"] = df["contracttype"].str.strip()

df["paymentmethod"] = df["paymentmethod"].str.strip()

df["churn"] = (
    df["churn"]
    .str.strip()
    .str.capitalize()
)

print("Contract types:")
print(df["contracttype"].unique())

print("\nPayment methods:")
print(df["paymentmethod"].unique())

print("\nChurn values:")
print(df["churn"].unique())

Contract types:
<StringArray>
['Month-to-Month', 'One Year', 'Two Year']
Length: 3, dtype: str

Payment methods:
<StringArray>
['Credit Card', 'Bank Transfer', 'UPI', 'Debit Card']
Length: 4, dtype: str

Churn values:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [75]:
numeric_columns = [
    "age",
    "tenuremonths",
    "monthlycharges",
    "totalcharges",
    "supporttickets"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

print("Numeric columns converted successfully!")

Numeric columns converted successfully!

In [76]:
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
customerid          0
gender              0
age                 0
tenuremonths        0
subscriptiontype    0
monthlycharges      0
totalcharges        0
contracttype        0
supporttickets      0
paymentmethod       0
churn               0
dtype: int64

In [77]:
print("==========================================")
print("       FINAL DATA VALIDATION")
print("==========================================")

# Dataset size
print("\n1. Dataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Missing values
print("\n2. Missing Values:")
print(df.isnull().sum())

# Duplicate rows
print("\n3. Duplicate Rows:")
print(df.duplicated().sum())

# Duplicate Customer IDs
print("\n4. Duplicate Customer IDs:")
print(df["customerid"].duplicated().sum())

# Data types
print("\n5. Data Types:")
print(df.dtypes)

# Column names
print("\n6. Column Names:")
print(df.columns.tolist())

print("\n==========================================")
print("       VALIDATION COMPLETED")
print("==========================================")

==========================================
       FINAL DATA VALIDATION
==========================================

1. Dataset Shape:
Rows: 15
Columns: 11

2. Missing Values:
customerid          0
gender              0
age                 0
tenuremonths        0
subscriptiontype    0
monthlycharges      0
totalcharges        0
contracttype        0
supporttickets      0
paymentmethod       0
churn               0
dtype: int64

3. Duplicate Rows:
0

4. Duplicate Customer IDs:
0

5. Data Types:
customerid              str
gender                  str
age                   int64
tenuremonths          int64
subscriptiontype        str
monthlycharges      float64
totalcharges        float64
contracttype            str
supporttickets        int64
paymentmethod           str
churn                   str
dtype: object

6. Column Names:
['customerid', 'gender', 'age', 'tenuremonths', 'subscriptiontype', 'monthlycharges', 'totalcharges', 'contracttype', 'supporttickets', 'paymentmethod', 'churn']

==========================================
       VALIDATION COMPLETED
==========================================

In [78]:
# Display the first 10 rows
display(df.head(10))

,customerid,gender,age,tenuremonths,subscriptiontype,monthlycharges,totalcharges,contracttype,supporttickets,paymentmethod,churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes
5,CUST-1006,Male,31,18,Basic,49.99,899.82,One Year,2,UPI,No
6,CUST-1007,Female,23,3,Basic,49.99,149.97,Month-to-Month,6,Credit Card,Yes
7,CUST-1008,Male,60,48,Enterprise,149.99,7199.52,Two Year,1,Bank Transfer,No
8,CUST-1009,Female,38,15,Pro,79.99,1199.85,One Year,2,Credit Card,No
9,CUST-1010,Male,27,4,Basic,49.99,199.96,Month-to-Month,4,UPI,Yes

In [79]:
# Display the complete dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        15 non-null     str
 1   gender            15 non-null     str
 2   age               15 non-null     int64
 3   tenuremonths      15 non-null     int64
 4   subscriptiontype  15 non-null     str
 5   monthlycharges    15 non-null     float64
 6   totalcharges      15 non-null     float64
 7   contracttype      15 non-null     str
 8   supporttickets    15 non-null     int64
 9   paymentmethod     15 non-null     str
 10  churn             15 non-null     str
dtypes: float64(2), int64(3), str(6)
memory usage: 1.4 KB

In [80]:
# Display statistical information
df.describe()

             age  tenuremonths  monthlycharges  totalcharges  supporttickets
count  15.000000     15.000000       15.000000     15.000000       15.000000
mean   39.066667     18.800000       84.656667   2088.478667        2.533333
std    11.392144     14.333776       42.739521   2407.365767        1.922300
min    23.000000      2.000000       49.990000     99.980000        0.000000
25%    30.000000      7.000000       49.990000    449.910000        1.000000
50%    38.000000     15.000000       79.990000   1099.780000        2.000000
75%    47.000000     27.000000      114.990000   3209.730000        4.000000
max    60.000000     48.000000      149.990000   7199.520000        6.000000

In [81]:
# Name of the cleaned CSV file
output_file = "cleaned_customer_churn.csv"

# Export the cleaned dataframe to CSV
df.to_csv(output_file, index=False)

print("Cleaned CSV file created successfully!")
print("File name:", output_file)

Cleaned CSV file created successfully!
File name: cleaned_customer_churn.csv

In [82]:
import os

print("CSV saved at:")
print(os.path.abspath("cleaned_customer_churn.csv"))

CSV saved at:
C:\Users\Vaishnavi\cleaned_customer_churn.csv

In [83]:
# Load the exported CSV
cleaned_df = pd.read_csv("cleaned_customer_churn.csv")

print("Cleaned CSV loaded successfully!")

print("\nShape:")
print(cleaned_df.shape)

print("\nFirst 5 rows:")
display(cleaned_df.head())

Cleaned CSV loaded successfully!

Shape:
(15, 11)

First 5 rows:

,customerid,gender,age,tenuremonths,subscriptiontype,monthlycharges,totalcharges,contracttype,supporttickets,paymentmethod,churn
0,CUST-1001,Female,34,12,Basic,49.99,599.88,Month-to-Month,3,Credit Card,Yes
1,CUST-1002,Male,45,24,Pro,79.99,1919.76,One Year,1,Bank Transfer,No
2,CUST-1003,Female,29,6,Basic,49.99,299.94,Month-to-Month,5,UPI,Yes
3,CUST-1004,Male,52,36,Enterprise,149.99,5399.64,Two Year,0,Credit Card,No
4,CUST-1005,Female,41,8,Pro,79.99,639.92,Month-to-Month,4,Debit Card,Yes

In [84]:
print("\nMissing values:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows:")
print(cleaned_df.duplicated().sum())

Missing values:
customerid          0
gender              0
age                 0
tenuremonths        0
subscriptiontype    0
monthlycharges      0
totalcharges        0
contracttype        0
supporttickets      0
paymentmethod       0
churn               0
dtype: int64

Duplicate rows:
0